version: '3.8'

services:
  WeatherMock:
    image: weathermock
    container_name: weathermock
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:80"
